# Generated by Django 5.1.1 on 2024-10-11 15:53

import django.contrib.auth.validators
from django.db import migrations, models


def generate_display_name(apps, schema):
    """default display name: copy username
    """
    user_model = apps.get_model("app", "User")
    for user in user_model.objects.all():
        if not user.display_name:
            user.display_name = user.username
        user.username = user.username.lower()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_ticket_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                help_text="Requis. 150 caractères maximum. Uniquement des lettres, nombres et les caractères «\xa0@\xa0», «\xa0.\xa0», «\xa0+\xa0», «\xa0-\xa0» et «\xa0_\xa0».",
                max_length=150,
                null=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="nom d’utilisateur",
            ),
        ),
        migrations.RunPython(generate_display_name),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                help_text="Requis. 150 caractères maximum. Uniquement des lettres, nombres et les caractères «\xa0@\xa0», «\xa0.\xa0», «\xa0+\xa0», «\xa0-\xa0» et «\xa0_\xa0».",
                null=False,
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="nom d’utilisateur",
            ),
        ),
    ]
